### ISSUE TITLE
DataStore insert should return model instance

### ISSUE THREAD

**Issue by ziacik** [bajankristof/nedb-models#1]
Hi.

Having a data store with model attached

```
class ItemStore extends Datastore {
	constructor() {
		super({
			filename: './db/item.db',
			autoload: true
		});
		this.attachModel(Item);
	}
}

```

when I do
`dataStore.insert(new Item(req.body)).then(inserted => ...)`

or even
`dataStore.insert(req.body).then(inserted => ...)`

I would expect that `inserted` is an instance of `Item`, but it is just a plain object instead.

**Comment by bajankristof** [comment]
Hi,
Thanks for submitting this issue.
You're absolutely right. This will be fixed as soon as I can spare some time for it.

**Comment by bajankristof** [comment]
Check out the 2.0 update as it brings a lot of new stuff into the bank whille also resolving this issue.
