### ISSUE TITLE
How could i access the DataStoreInstance from Model?

### ISSUE THREAD

**Issue by nickfan** [bajankristof/nedb-models#5]
in nedb-promises we could access instance by:

```
let datastore = Datastore.create('/path/to/db.db')
```
and call 
```
datastore.persistence.compactDatafile();
```
manually.

but in nedb-model

```
static datastore() {
      	return {
        	filename: 'books.db'
        }
    }
    
```

the static datastore only accept config object or could i pass a datastore instance?

and how could i get the datastore instance from nedb-model instance?

is there any example code?

**Comment by bajankristof** [comment]
Hi,

So it's not stated in the docs but you can actually return a (nedb-promises) Datastore instance in the static datastore method and then that will be used by the model

I'm not sure what you mean by:
> and how could i get the datastore instance from nedb-model instance?
Could you please explain a bit more?

**Comment by bajankristof** [comment]
I updated the docs accordingly: https://github.com/bajankristof/nedb-models/blob/master/docs.md#Model.datastore

**Comment by nickfan** [comment]
eg:
for my db model:

```
MyDemoModel extends Model{
  static datastore() {
    return {
      filename: './mydemo.db',
      inMemoryOnly: false,
      autoload: true,
      timestampData: true
    };
  }
}
```

i want to manually call the function

```
datastore.persistence.compactDatafile();
```

on the MyDemoModel to compact the db file.

how to achieve that?

maybe expose some function so we cloud access the datastore instance var.

```
// maybe something like this?

MyDemoModel.dbinstance().persistence.compactDatafile();

```

**Comment by bajankristof** [comment]
In your model you should do something like:
```js
const Datastore = require('nedb-models');

MyDemoModel extends Model {
  static datastore() {
    const datastore = Datastore.create({
      filename: './mydemo.db',
      inMemoryOnly: false,
      autoload: true,
      timestampData: true
    });
    datastore.persistance.compactDatafile();
    return datastore;
  }
}
```

**Comment by nickfan** [comment]
yes, thanks,i know that i could do that when we (construct/bootstrap) the model,but 

after we defined the model, how could i reference via model?

or i have to define the datastore outside like this?

```
const Datastore = require('nedb-promises');

const datastore = Datastore.create({
      filename: './mydemo.db',
      inMemoryOnly: false,
      autoload: true,
      timestampData: true
    });
MyDemoModel extends Model {
  static datastore() {
    return datastore;
  }
}

(async()=>{
let demoObj1 = await MyDemoModel.create({k1:1,k2:2});
let demoObj2 = await MyDemoModel.create({k1:2,k2:3});
// we have to define the datastore outside and reference it.
datastore.persistance.compactDatafile();
// how about build a static function to access the datastore instance via model like this?
MyDemoModel.dsinstance().persistance.compactDatafile();

})();
```

**Comment by bajankristof** [comment]
Oh okay I got it now, the datastore instance is stored at `${__class}.__datastore` so in this case `MyDemoModel.__datastore`
So you can call `MyDemoModel.__datastore.persistance.compactDatafile()`

**Comment by nickfan** [comment]
ok, thanks i got it.
