### ISSUE TITLE
i can't access the datastore instance via __datastore

### ISSUE THREAD

**Issue by nickfan** [bajankristof/nedb-models#6]
reference #5

today i just try to access the datastore instance via __datastore prop.

call MyDemoModel.__datastore.persistence.compactDatafile()

but console show's that :
```
TypeError: Cannot read property 'compactDatafile' of undefined
```

i print the __datastore property it's not the original nedb instance:
```
__datastore Datastore {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined }
persistence undefined
```

this is my test code:

```
const Datastore = require('nedb-promises');
const { Model } = require('nedb-models');
const datastore = Datastore.create({
  filename: './mydemo.db',
  inMemoryOnly: false,
  autoload: true,
  timestampData: true
});
class MyDemoModel extends Model {
  static datastore() {
    return datastore;
  }

}

(async()=>{
  // eslint-disable-next-line no-unused-vars
  let demoObj1 = await MyDemoModel.create({k1:1,k2:2});
  // eslint-disable-next-line no-unused-vars
  let demoObj2 = await MyDemoModel.create({k1:2,k2:3});
//   datastore.persistance.compactDatafile();
  console.log("__datastore",MyDemoModel.__datastore);
  console.log("persistence",MyDemoModel.__datastore.persistence);
  MyDemoModel.__datastore.persistence.compactDatafile();
})().catch(err=>{
  console.error(err);
});
```

**Comment by nickfan** [comment]
ok,i read the code,and found the solution:

```
MyDemoModel.__datastore.__original.persistence.compactDatafile();
```

**Comment by nickfan** [comment]
and i still suggest to provide a static method to access the __datastore or the __original property,
i build my app a base model extends nedb-model,and the AppdemoModel extends my BaseModel.
i could not access the __datastore via AppdemoModel.__datastore.

**Comment by bajankristof** [comment]
Hi, sorry for the delayed reply, autumn is always busy because of all the black fridays...
I will try to look into this ASAP!

**Comment by nickfan** [comment]
Thanks for your concern.

**Comment by bajankristof** [comment]
Hi again,
so I thought about it and realized that this `MyDemoModel.__datastore.__original.persistence.compactDatafile();` is not a very optimal way of setting up the datastore.

Check out the [static datastore](https://github.com/bajankristof/nedb-models/blob/master/docs.md#Model.datastore) method. 

In there you could create the datastore and set up the desired original properties. This way the datastore is only created when you actually use the model.
